name: terraform-snap
version: 0.9.11
summary: build, change, and version infrastructure safely and efficiently
description: |
  Terraform is a tool for building, changing, and versioning infrastructure
  safely and efficiently. Terraform can manage existing and popular service
  providers as well as custom in-house solutions.

grade: stable
confinement: strict

apps:
  terraform:
    command: terraform
    plugs: [home, network, network-bind]
  terraform-provider-zabbix:
    command: terraform-provider-zabbix
    plugs: [home, network, network-bind]

parts:
  terraform:
    source: https://github.com/hashicorp/terraform.git
    source-tag: v0.9.11
    plugin: go
    go-importpath: github.com/hashicorp/terraform
    go-packages: [github.com/hashicorp/terraform]
    go-buildtags: [dev]
    after: [go]
  terraform-provider-zabbix:
    source: https://github.com/dainis/terraform-provider-zabbix.git
    source-tag: master
    plugin: go
    go-importpath: github.com/dainis/terraform-provider-zabbix
    go-packages: [github.com/dainis/terraform-provider-zabbix]
    go-buildtags: [master]
    after: [go]
  go:
    source-tag: go1.8.1
